spring:
  application:
    name: licensingservice
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/