spring:
  application:
    name: licensingservice
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      organizationService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        failureRateThreshold: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10

  retry:
    instances:
      organizationService:
        maxAttempts: 3
        waitDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
